version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spc_backend
    command: gunicorn spc_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=spc_db
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_HOST=db
      - REDIS_URL=redis://redis:6379/1
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: spc_db
    environment:
      POSTGRES_DB: spc_db
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: spc_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:stable-alpine
    container_name: spc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/public:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  postgres_data:
